<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      function fetch() {
        return new Promise((resolve, reject) => {
          // 请求会在 1 秒后失败
          setTimeout(() => {
            reject("err");
          }, 1000);
        });
      }
      // load 函数接收⼀个 onError 回调函数
      function load(onError) {
        // 请求接⼝，得到 Promise 实例
        const p = fetch();
        // 捕获错误
        return p.catch((err) => {
          // 当错误发⽣时，返回⼀个新的 Promise 实例，并调⽤ onError 回调，同时将 retry 函数作为 onError 回调的参数
          return new Promise((resolve, reject) => {
            // retry 函数，⽤来执⾏重试的函数，执⾏该函数会重新调⽤ load 函数并发送请求
            const retry = () => resolve(load(onError));
            const fail = () => reject(err);
            onError(retry, fail);
          });
        });
      }

      load((retry) => {
        retry();
        console.log(99);
      }).then((res) => {
        console.log(res);
      });
    </script>
  </body>
</html>
